spring:
  application:
    name: back-end
  datasource:
    url: jdbc:mysql://localhost:3306/smart_clinic_db?usessl=false
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: smart_clinic_db
      authentication-database: admin
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8

management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
api:
  path: /
jwt:
  secret: $!@#$^%$$$%####$DDCPN0234FCFDPD8670M
