name: Compile Java Backend

on: [push]

jobs:
  compile-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Compile with Maven
        run: |
          cd app
          mvn clean compile
