name: Compile Java Backend

on: [push]

jobs:
  compile-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Compile with Maven
        run: |
          cd app
          ./mvnw clean compile
